name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install just
        uses: extractions/setup-just@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v6

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Install shfmt
        run: |
          curl -sS https://webi.sh/shfmt | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Initialize TFLint
        run: tflint --init --chdir=terraform

      - name: Run checks
        run: just ci
